# This is the plugin Version, do not touch!
version: "v1.0.0"

# Basic Configuration Inputs.
prefix: "&7[Prefix]"

# Player Obtainable Ranks Section

Traveler:
  Blocks: "15000"
Miner:
  Blocks: "5000"